sudo: required

env:
  global:
    - GOSS_PATH="./goss"
    - DGOSS_PATH="./dgoss"
  jobs:
    - PHP_VARIANT=7.4-alpine
    - PHP_VARIANT=7.4
    - PHP_VARIANT=8.0
    - PHP_VARIANT=8.1

services:
  - docker

before_install:
  - curl -L https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss -o dgoss
  - curl -L https://github.com/aelsabbahy/goss/releases/download/v0.3.9/goss-linux-amd64 -o goss
  - chmod 755 dgoss goss

script:
  - ./test.sh localhost
